import puppeteer from "puppeteer-core";

const browser = await puppeteer.launch({ executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless:true, args:["--no-sandbox"] });
const page = await browser.newPage();
await page.setViewport({width:1440,height:1000,deviceScaleFactor:1});
await page.goto("http://127.0.0.1:5173",{waitUntil:"networkidle0"});
await page.evaluate(()=>localStorage.clear());
await page.reload({waitUntil:"networkidle0"});
await page.screenshot({path:"/tmp/forge-welcome-dark.png",fullPage:true});
await page.evaluate(()=>{document.documentElement.dataset.theme="light"});
await page.screenshot({path:"/tmp/forge-welcome-light.png",fullPage:true});
await page.evaluate(()=>{
  const profile={id:"audit_user",fullName:"UI Audit",username:"ui_audit",level:"Complete Beginner",goal:"Become Full-Stack AI Developer",dailyGoal:"1 Hour",speed:"Normal",createdAt:new Date().toISOString()};
  localStorage.setItem("forge-local-profiles-v1",JSON.stringify([profile]));
  localStorage.setItem("forge-active-profile-v1",profile.id);
  localStorage.setItem("forge-theme","dark");
});
await page.goto("http://127.0.0.1:5173/",{waitUntil:"networkidle0"});
await page.screenshot({path:"/tmp/forge-dashboard-dark.png",fullPage:true});
await page.click('button[aria-label="Toggle theme"]');
await page.screenshot({path:"/tmp/forge-dashboard-light.png",fullPage:true});
await page.evaluate(()=>document.querySelectorAll("nav button")[2].click());
await new Promise(resolve=>setTimeout(resolve,200));
await page.screenshot({path:"/tmp/forge-roadmap-light.png",fullPage:true});
await page.click('button[aria-label="Toggle theme"]');
await page.screenshot({path:"/tmp/forge-roadmap-dark.png",fullPage:true});
await page.evaluate(()=>document.querySelectorAll("nav button")[1].click());
await new Promise(resolve=>setTimeout(resolve,200));
await page.screenshot({path:"/tmp/forge-lesson-dark.png",fullPage:true});
await page.evaluate(()=>{
  document.documentElement.dataset.theme="light";
  localStorage.setItem("forge-theme","light");
});
await page.screenshot({path:"/tmp/forge-lesson-light.png",fullPage:true});
await page.setViewport({width:390,height:844,deviceScaleFactor:1});
await page.screenshot({path:"/tmp/forge-lesson-mobile.png",fullPage:false});
await page.click(".learning-focus .back-link");
await new Promise(resolve=>setTimeout(resolve,200));
await page.click('button[aria-label="Open Orientation & Developer Setup"]');
await page.evaluate(()=>{
  const target=[...document.querySelectorAll("button")].find(button=>button.textContent?.includes("Hardware, memory and storage"));
  target?.click();
});
await page.waitForSelector(".catalog-lesson");
await new Promise(resolve=>setTimeout(resolve,500));
await page.screenshot({path:"/tmp/forge-catalog-mobile.png",fullPage:false});
await page.setViewport({width:1470,height:956,deviceScaleFactor:1});
await page.evaluate(()=>{
  document.documentElement.dataset.theme="dark";
  localStorage.setItem("forge-theme","dark");
  window.scrollTo(0,0);
  const target=[...document.querySelectorAll("button")].find(button=>button.textContent?.includes("npm and package management"));
  target?.click();
});
await page.waitForFunction(()=>document.body.textContent?.includes("What npm manages"));
await new Promise(resolve=>setTimeout(resolve,300));
await page.screenshot({path:"/tmp/forge-npm-desktop.png",fullPage:false});
await page.$eval(".interactive-example-lab",element=>element.scrollIntoView({block:"start"}));
await new Promise(resolve=>setTimeout(resolve,200));
await page.screenshot({path:"/tmp/forge-npm-lab-desktop.png",fullPage:false});
await page.setViewport({width:390,height:844,deviceScaleFactor:1});
await page.$eval(".interactive-example-lab",element=>element.scrollIntoView({block:"start"}));
await new Promise(resolve=>setTimeout(resolve,200));
await page.screenshot({path:"/tmp/forge-npm-lab-mobile.png",fullPage:false});
await page.setViewport({width:1470,height:956,deviceScaleFactor:1});
await page.goto("http://127.0.0.1:5173/projects",{waitUntil:"networkidle0"});
await page.screenshot({path:"/tmp/forge-projects-desktop.png",fullPage:false});
await page.setViewport({width:390,height:844,deviceScaleFactor:1});
await page.evaluate(()=>{
  const closeButton=document.querySelector(".sidebar.open .close-mobile");
  if (closeButton instanceof HTMLButtonElement) closeButton.click();
});
await new Promise(resolve=>setTimeout(resolve,150));
await page.screenshot({path:"/tmp/forge-projects-mobile.png",fullPage:false});
await page.setViewport({width:1470,height:956,deviceScaleFactor:1});
await page.goto("http://127.0.0.1:5173/interview",{waitUntil:"networkidle0"});
await page.screenshot({path:"/tmp/forge-interview-academy-desktop.png",fullPage:false});
await page.evaluate(()=>{
  const start=[...document.querySelectorAll("button")].find(button=>button.textContent?.includes("Quick practice"));
  if (start instanceof HTMLButtonElement) start.click();
});
await page.waitForSelector(".interview-question-pro");
await page.screenshot({path:"/tmp/forge-interview-session-desktop.png",fullPage:false});
await page.click(".interview-session-toolbar .back-link");
await page.setViewport({width:390,height:844,deviceScaleFactor:1});
await page.screenshot({path:"/tmp/forge-interview-academy-mobile.png",fullPage:false});
await browser.close();
console.log("Theme screenshots saved in /tmp/forge-*.png");
