export type FrameworkTrack = "common" | "react" | "angular";
export type FrontendFrameworkPath = "react" | "angular" | "both";
export type CurriculumModule = {
  id: string;
  title: string;
  topics: string[];
  track?: FrameworkTrack;
};
export type CurriculumPhase = {
  id: string;
  order: number;
  title: string;
  description: string;
  duration: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  modules: CurriculumModule[];
  lessonIds: string[];
};

const module = (
  id: string,
  title: string,
  topics: string[],
  track?: FrameworkTrack,
): CurriculumModule => ({ id, title, topics, track });

export const curriculumPhases: CurriculumPhase[] = [
  {
    id: "orientation",
    order: 0,
    title: "Orientation & Developer Setup",
    description:
      "Start from zero. Learn how computers and the web work, set up your tools, use Git, and fix simple problems.",
    duration: "2 weeks",
    difficulty: "Beginner",
    lessonIds: ["day-1-computers", "day-2-web"],
    modules: [
      module("computer-basics", "Computer & Software Basics", [
        "How computers execute instructions",
        "Hardware, memory and storage",
        "Programs and algorithms",
        "Operating systems and files",
      ]),
      module("web-basics", "Internet & Web Basics", [
        "How the web works",
        "Client and server",
        "DNS, URLs and HTTP",
        "Browsers and developer tools",
      ]),
      module("developer-setup", "Developer Setup", [
        "Terminal and file system",
        "VS Code and extensions",
        "Git and GitHub",
        "npm and package management",
        "Debugging mindset",
      ]),
    ],
  },
  {
    id: "web",
    order: 1,
    title: "Web Fundamentals",
    description:
      "Build clear, accessible websites with HTML and CSS that work on phones, tablets, and computers.",
    duration: "4 weeks",
    difficulty: "Beginner",
    lessonIds: ["day-3-html", "day-4-semantic-html", "day-5-css"],
    modules: [
      module("html", "HTML", [
        "HTML document structure",
        "Text, links and images",
        "Lists and tables",
        "Forms and validation",
        "Semantic and accessible HTML",
        "Metadata and SEO",
      ]),
      module("css", "CSS", [
        "CSS foundations and the box model",
        "Cascade and specificity",
        "Typography, colors and units",
        "Display and positioning",
        "Flexbox",
        "Grid",
        "Responsive design",
        "Transitions and animation",
        "CSS architecture",
      ]),
      module("web-projects", "Web Projects", [
        "Personal page",
        "Landing page",
        "Responsive portfolio",
        "Business website",
      ]),
    ],
  },
  {
    id: "javascript",
    order: 2,
    title: "JavaScript",
    description:
      "Learn JavaScript basics, change web pages, load data, organize code, write tests, and keep apps safe.",
    duration: "7 weeks",
    difficulty: "Beginner",
    lessonIds: ["day-6-javascript"],
    modules: [
      module("js-foundations", "Language Foundations", [
        "Variables, values, and functions",
        "Types and conversion",
        "Operators and expressions",
        "Conditions and switch",
        "Loops",
        "Scope and hoisting",
      ]),
      module("js-data", "Data & Functions", [
        "Arrays",
        "Objects",
        "Destructuring",
        "Spread and rest",
        "Map and Set",
        "Higher-order functions",
        "Closures",
        "Recursion",
      ]),
      module("js-browser", "Browser JavaScript", [
        "DOM",
        "Events",
        "Forms and validation",
        "Modules",
        "Web storage",
        "Accessibility with JavaScript",
      ]),
      module("js-async", "Asynchronous JavaScript", [
        "Promises",
        "Async and await",
        "Fetch and HTTP APIs",
        "Event loop",
        "Call stack",
        "Cancellation and errors",
      ]),
      module("js-advanced", "Advanced JavaScript", [
        "Prototypes and classes",
        "OOP and functional programming",
        "Design patterns",
        "Memory and performance",
        "Testing",
        "Security basics",
      ]),
    ],
  },
  {
    id: "typescript",
    order: 3,
    title: "TypeScript Systems",
    description:
      "Use TypeScript to catch mistakes early and keep large apps easier to understand and change.",
    duration: "4 weeks",
    difficulty: "Intermediate",
    lessonIds: [],
    modules: [
      module("ts-foundations", "TypeScript Foundations", [
        "Setup and compiler",
        "Annotations and inference",
        "Primitive types",
        "Arrays, tuples and enums",
        "Objects and functions",
      ]),
      module("ts-type-system", "Type System", [
        "Interfaces and aliases",
        "Unions and intersections",
        "Literal types",
        "Narrowing",
        "unknown, never and void",
      ]),
      module("ts-advanced", "Advanced Types", [
        "Generics and constraints",
        "keyof and typeof",
        "Indexed access",
        "Conditional types",
        "Mapped and utility types",
      ]),
      module("ts-production", "Production TypeScript", [
        "API typing",
        "React typing",
        "Library typing",
        "SDK design",
        "Architecture and testing",
      ]),
    ],
  },
  {
    id: "frontend",
    order: 4,
    title: "Frontend Engineering",
    description:
      "Learn the shared web skills first. Then choose React, Angular, or both and build complete real-world projects.",
    duration: "14–24 weeks",
    difficulty: "Intermediate",
    lessonIds: [],
    modules: [
      module("frontend-platform", "Shared · Browser & Platform", [
        "Browser rendering pipeline",
        "DOM, CSSOM and render tree",
        "JavaScript runtime and event loop",
        "HTTP, caching and browser networking",
        "REST and API contracts",
        "Fetch, cancellation and retries",
        "Cookies, storage and browser state",
        "ES modules and package resolution",
        "Vite, bundling and source maps",
        "Git and pull-request workflow",
      ], "common"),
      module("frontend-ui", "Shared · UI Engineering", [
        "Semantic component design",
        "Responsive layout systems",
        "Accessible interaction patterns",
        "Forms, validation and error UX",
        "Design tokens and theming",
        "Reusable component APIs",
        "Internationalization and localization",
        "Loading, empty and failure states",
        "Progressive enhancement",
      ], "common"),
      module("frontend-quality", "Shared · Quality & Security", [
        "TypeScript for frontend systems",
        "Unit and component testing strategy",
        "Integration and end-to-end testing",
        "Test doubles and network mocking",
        "Accessibility testing",
        "Frontend threat modeling",
        "XSS, CSRF and content security policy",
        "Authentication and authorization UX",
        "Dependency and supply-chain security",
        "Debugging with browser DevTools",
      ], "common"),
      module("frontend-production", "Shared · Performance & Architecture", [
        "Core Web Vitals",
        "Performance profiling",
        "Bundle analysis and code splitting",
        "Images, fonts and asset optimization",
        "Rendering and memory performance",
        "Frontend architecture boundaries",
        "Design systems at scale",
        "Logging, analytics and observability",
        "CI/CD and preview environments",
        "Production deployment and rollback",
      ], "common"),

      module("react-core", "React · Foundations", [
        "How React works",
        "JSX and rendering",
        "Function components",
        "Props and one-way data flow",
        "Local state",
        "Events",
        "Conditional rendering",
        "Lists and stable keys",
        "Composition and children",
        "Controlled and uncontrolled inputs",
      ], "react"),
      module("react-hooks", "React · Hooks & State", [
        "useState and state identity",
        "useEffect and synchronization",
        "Effect cleanup and races",
        "useRef",
        "useMemo and useCallback",
        "Context API",
        "Reducers",
        "Custom hooks",
        "Client and server state",
        "State management trade-offs",
      ], "react"),
      module("react-applications", "React · Application Development", [
        "Routing and nested layouts",
        "Data loading and mutations",
        "API client architecture",
        "Forms and schema validation",
        "Authentication flows",
        "Authorization and protected routes",
        "Optimistic updates",
        "Caching and invalidation",
        "Real-time React applications",
        "Error, loading and recovery UX",
      ], "react"),
      module("react-quality", "React · Testing & Debugging", [
        "React Testing Library",
        "Component and hook testing",
        "Integration testing",
        "Mock Service Worker",
        "End-to-end React testing",
        "React DevTools",
        "Render-loop debugging",
        "Stale closures and effect bugs",
        "Accessible React testing",
      ], "react"),
      module("react-advanced", "React · Advanced & Internals", [
        "Render and commit phases",
        "Reconciliation",
        "Concurrent rendering concepts",
        "Suspense",
        "Error boundaries",
        "Portals and imperative escape hatches",
        "Compound components",
        "Headless component patterns",
        "Performance profiling and memoization",
        "Large React application architecture",
      ], "react"),
      module("nextjs", "React · Next.js & Production", [
        "Next.js application routing",
        "Server and client components",
        "Server-side rendering",
        "Static generation",
        "Streaming and Suspense",
        "Server actions and mutations",
        "Caching and revalidation",
        "Next.js authentication and security",
        "SEO and metadata",
        "React production deployment",
      ], "react"),
      module("react-projects", "React · Projects & Interviews", [
        "React task manager project",
        "React commerce project",
        "React analytics SaaS project",
        "React performance incident lab",
        "React legacy refactoring lab",
        "React architecture case study",
        "React interview questions",
        "React capstone assessment",
      ], "react"),

      module("angular-core", "Angular · Foundations", [
        "How Angular works",
        "Angular CLI and workspace",
        "Standalone components",
        "Templates and binding",
        "Inputs and outputs",
        "Control flow",
        "Lifecycle hooks",
        "Directives",
        "Pipes",
        "Content projection",
      ], "angular"),
      module("angular-di", "Angular · Services & Dependency Injection", [
        "Services and providers",
        "How dependency injection works",
        "Injection tokens",
        "Provider scopes",
        "Environment providers",
        "Route-level providers",
        "Reusable service design",
        "Configuration and environments",
        "Global error handling",
        "Angular logging strategy",
      ], "angular"),
      module("angular-reactivity", "Angular · RxJS & Signals", [
        "Observable fundamentals",
        "Subject and BehaviorSubject",
        "ReplaySubject",
        "How RxJS operators work",
        "switchMap, mergeMap, concatMap and exhaustMap",
        "combineLatest and forkJoin",
        "RxJS error handling",
        "Cancellation and teardown",
        "shareReplay and multicasting",
        "Signals",
        "computed and effect",
        "Signals versus Observables",
      ], "angular"),
      module("angular-applications", "Angular · Application Development", [
        "Angular Router",
        "Nested and lazy routes",
        "Route guards",
        "Template-driven forms",
        "Reactive forms",
        "Custom form controls",
        "HttpClient",
        "HTTP interceptors",
        "Authentication and authorization",
        "API errors and recovery",
      ], "angular"),
      module("angular-state", "Angular · State & Architecture", [
        "Local component state",
        "Signals state architecture",
        "RxJS state architecture",
        "NgRx fundamentals",
        "Store, actions and reducers",
        "Selectors and effects",
        "Server-state caching",
        "Feature-based architecture",
        "Core, shared and domain boundaries",
        "Enterprise Angular architecture",
      ], "angular"),
      module("angular-quality", "Angular · Testing & Debugging", [
        "Angular unit testing",
        "Component testing",
        "Service testing",
        "HTTP testing",
        "Router testing",
        "Mocking dependencies",
        "Integration testing",
        "Angular end-to-end testing",
        "Angular DevTools",
        "Change-detection debugging",
        "RxJS leak debugging",
        "Meaningful test coverage",
      ], "angular"),
      module("angular-advanced", "Angular · Advanced & Performance", [
        "Change detection internals",
        "OnPush strategy",
        "Stable identity and track expressions",
        "Lazy loading and deferrable views",
        "Bundle analysis and code splitting",
        "Virtual scrolling",
        "Large-table performance",
        "Web Workers",
        "SSR and hydration",
        "Dynamic components",
        "Reusable Angular libraries",
        "Angular performance incident lab",
      ], "angular"),
      module("angular-production", "Angular · Production Systems", [
        "Angular security model",
        "XSS prevention and sanitization",
        "Enterprise authentication",
        "Accessibility in Angular",
        "Internationalization",
        "Angular build configuration",
        "CI/CD for Angular",
        "Observability and telemetry",
        "Angular production deployment",
        "Upgrade and migration strategy",
      ], "angular"),
      module("angular-projects", "Angular · Projects & Interviews", [
        "Angular admin dashboard project",
        "Angular component library project",
        "Real-time Angular dashboard project",
        "Enterprise Angular application project",
        "Angular production incident labs",
        "Angular architecture case study",
        "Angular interview questions",
        "Angular capstone assessment",
      ], "angular"),
    ],
  },
  {
    id: "backend",
    order: 5,
    title: "Backend & Data",
    description:
      "Build safe APIs and services. Store data, handle background work, and add live updates.",
    duration: "8 weeks",
    difficulty: "Intermediate",
    lessonIds: [],
    modules: [
      module("node", "Node.js", [
        "Runtime and modules",
        "File system",
        "Events and streams",
        "HTTP",
        "npm packages",
      ]),
      module("apis", "APIs with Express", [
        "REST design",
        "Routing and controllers",
        "Services and middleware",
        "Validation and errors",
        "Testing and logging",
      ]),
      module("security", "Identity & Security", [
        "Authentication and authorization",
        "Cookies and sessions",
        "JWT concepts",
        "OAuth concepts",
        "Rate limiting and secure defaults",
      ]),
      module("sql", "SQL & PostgreSQL", [
        "Tables and data types",
        "CRUD and filtering",
        "JOINs and aggregation",
        "Constraints and transactions",
        "Normalization and schema design",
        "Indexes and query optimization",
      ]),
      module("distributed-backend", "Scalable Backend", [
        "Redis and caching",
        "Queues and background jobs",
        "WebSockets",
        "Real-time systems",
      ]),
      module("backend-internals", "Node.js Internals & Performance", [
        "Event-loop phases",
        "Streams and backpressure",
        "Worker threads",
        "Process and memory profiling",
        "Connection pooling",
        "CPU-bound versus I/O-bound work",
        "Memory leaks",
        "Load testing and capacity",
      ]),
      module("backend-data-systems", "Advanced Data Systems", [
        "Document databases",
        "Key-value databases",
        "NoSQL data modeling",
        "Isolation levels",
        "Locking and deadlocks",
        "Read replicas",
        "Database migrations",
        "Backup and point-in-time recovery",
      ]),
      module("backend-architecture", "Backend Architecture", [
        "Modular monoliths",
        "Hexagonal architecture",
        "Domain-driven design foundations",
        "Idempotency",
        "Distributed transactions and sagas",
        "Outbox and inbox patterns",
        "API versioning",
        "Service ownership and contracts",
      ]),
      module("backend-incidents", "Backend Projects & Incident Labs", [
        "Production CRUD API project",
        "Authentication service project",
        "Real-time collaboration project",
        "API 500-error incident",
        "Database connection exhaustion incident",
        "Duplicate request incident",
        "Queue backlog incident",
        "Backend capstone assessment",
      ]),
    ],
  },
  {
    id: "dsa",
    order: 6,
    title: "Data Structures & Algorithms",
    description:
      "Learn how to break down coding problems, choose useful data structures, write faster solutions, and explain them in interviews.",
    duration: "10 weeks",
    difficulty: "Intermediate",
    lessonIds: [],
    modules: [
      module("dsa-foundations", "Problem-Solving Foundations", [
        "Problem decomposition",
        "Pseudocode and dry runs",
        "Time and space complexity",
        "Big O, Omega and Theta",
        "Best, average and worst cases",
        "Amortized analysis",
        "Recursion and call stacks",
        "Iteration versus recursion",
      ]),
      module("dsa-linear", "Arrays, Strings & Linear Structures", [
        "Arrays and dynamic arrays",
        "Strings and character processing",
        "Two pointers",
        "Sliding window",
        "Prefix sums",
        "Linked lists",
        "Stacks",
        "Queues and deques",
        "Monotonic stacks and queues",
      ]),
      module("dsa-hashing", "Hashing, Trees & Heaps", [
        "Hash tables and collision handling",
        "Sets and frequency maps",
        "Binary trees",
        "Tree traversals",
        "Binary search trees",
        "Balanced-tree concepts",
        "Tries",
        "Heaps and priority queues",
        "Union-find",
      ]),
      module("dsa-graphs", "Graphs", [
        "Graph representations",
        "Breadth-first search",
        "Depth-first search",
        "Topological sorting",
        "Shortest paths",
        "Dijkstra algorithm",
        "Minimum spanning trees",
        "Cycle detection",
        "Connected components",
      ]),
      module("dsa-algorithms", "Algorithms & Techniques", [
        "Linear and binary search",
        "Sorting algorithms",
        "Divide and conquer",
        "Greedy algorithms",
        "Backtracking",
        "Dynamic programming foundations",
        "One-dimensional dynamic programming",
        "Grid and sequence dynamic programming",
        "Bit manipulation",
      ]),
      module("dsa-professional", "Professional Problem Solving", [
        "Choosing structures from constraints",
        "Correctness proofs and invariants",
        "Property-based testing",
        "Memory and cache behavior",
        "Production algorithm trade-offs",
        "Streaming and approximate algorithms",
        "Debugging algorithmic failures",
        "Communicating solutions in interviews",
      ]),
      module("dsa-interviews", "Interview Tracks & Assessments", [
        "Beginner coding set",
        "Junior coding set",
        "Mid-level coding set",
        "Advanced coding set",
        "Timed coding assessment",
        "Algorithm debugging assessment",
        "Mock coding interview",
        "DSA capstone assessment",
      ]),
    ],
  },
  {
    id: "system-design",
    order: 7,
    title: "System Design",
    description:
      "Learn how large apps handle more users, stay reliable, protect data, and recover when something fails.",
    duration: "6 weeks",
    difficulty: "Advanced",
    lessonIds: [],
    modules: [
      module("design-foundations", "Foundations", [
        "Networking and HTTP",
        "Latency and throughput",
        "Availability and reliability",
        "Vertical and horizontal scaling",
      ]),
      module("design-components", "System Components", [
        "Load balancers and CDNs",
        "Caching",
        "Replication and partitioning",
        "Queues and Pub/Sub",
        "API gateways and rate limiting",
      ]),
      module("design-architecture", "Architecture", [
        "Monoliths and microservices",
        "Event-driven systems",
        "Consistency and CAP",
        "Observability",
        "Fault tolerance and recovery",
        "LLD and HLD",
      ]),
      module("design-exercises", "Design Exercises", [
        "URL shortener",
        "Chat system",
        "File storage",
        "Social feed",
        "Search system",
        "AI chat application",
      ]),
      module("distributed-systems", "Distributed Systems", [
        "Time, clocks and ordering",
        "Consensus foundations",
        "Leader election",
        "Quorums",
        "Eventual consistency",
        "Conflict resolution",
        "Distributed locks",
        "Exactly-once processing myths",
        "Multi-region data systems",
      ]),
      module("reliability-architecture", "Reliability & Security Architecture", [
        "SLOs, SLIs and error budgets",
        "Capacity planning",
        "Bulkheads and circuit breakers",
        "Disaster recovery",
        "Zero-downtime migrations",
        "Threat modeling at system scale",
        "Secrets and key management",
        "Incident command and postmortems",
        "Cost and performance trade-offs",
      ]),
      module("staff-architecture", "Staff & Principal Architecture", [
        "Technical RFCs",
        "Architecture decision records",
        "Build versus buy decisions",
        "Platform engineering",
        "API governance",
        "Legacy modernization",
        "Cross-team migration strategy",
        "Architecture governance",
        "Global system case study",
      ]),
    ],
  },
  {
    id: "python",
    order: 8,
    title: "Python for AI",
    description:
      "Learn Python from the basics, then use it for data work, tested apps, and AI engineering.",
    duration: "5 weeks",
    difficulty: "Intermediate",
    lessonIds: [],
    modules: [
      module("python-core", "Python Foundations", [
        "Syntax and types",
        "Conditions and loops",
        "Functions",
        "Collections",
        "Modules and packages",
      ]),
      module("python-production", "Production Python", [
        "Virtual environments",
        "OOP",
        "Exceptions and files",
        "JSON and APIs",
        "Type hints and testing",
      ]),
      module("python-data", "Data Toolkit", [
        "NumPy",
        "Pandas",
        "Matplotlib",
        "Data preprocessing",
      ]),
      module("python-advanced", "Advanced Python", [
        "Iterators and generators",
        "Decorators",
        "Context managers",
        "Descriptors and data model",
        "Asyncio",
        "Concurrency and multiprocessing",
        "Profiling and optimization",
        "Packaging and publishing",
      ]),
      module("math-statistics", "Mathematics & Statistics for AI", [
        "Vectors and matrices",
        "Linear transformations",
        "Derivatives and gradients",
        "Probability foundations",
        "Random variables and distributions",
        "Expectation and variance",
        "Statistical inference",
        "Hypothesis testing",
        "Experiment design",
      ]),
      module("data-engineering", "Data Engineering Foundations", [
        "Data quality and validation",
        "ETL and ELT",
        "Batch and streaming data",
        "Data warehouses and lakes",
        "Columnar formats",
        "Workflow orchestration",
        "Data lineage",
        "Reproducible data pipelines",
      ]),
      module("python-projects", "Python & Data Projects", [
        "Python CLI project",
        "Typed API client project",
        "Data analysis project",
        "ETL pipeline project",
        "Python performance incident lab",
        "Python capstone assessment",
      ]),
    ],
  },
  {
    id: "machine-learning",
    order: 9,
    title: "Machine Learning",
    description:
      "Train and test machine-learning models with real data. Learn how to measure and improve their results.",
    duration: "6 weeks",
    difficulty: "Advanced",
    lessonIds: [],
    modules: [
      module("ml-foundations", "ML Foundations", [
        "AI vs ML vs deep learning",
        "Features and labels",
        "Training, validation and testing",
        "Supervised and unsupervised learning",
      ]),
      module("ml-models", "Models", [
        "Regression",
        "Classification",
        "Clustering",
        "Scikit-learn workflows",
      ]),
      module("ml-quality", "Model Quality", [
        "Metrics",
        "Overfitting and underfitting",
        "Bias and variance",
        "Cross-validation",
        "Feature engineering and hyperparameters",
      ]),
      module("ml-production", "Production Machine Learning", [
        "Experiment tracking",
        "Data and model versioning",
        "Training pipelines",
        "Batch and online inference",
        "Model serving",
        "Feature stores",
        "Data drift and concept drift",
        "Model monitoring",
        "Responsible AI and fairness",
      ]),
      module("ml-projects", "ML Projects & Incidents", [
        "Regression project",
        "Classification project",
        "Recommendation project",
        "Model leakage investigation",
        "Training-serving skew incident",
        "Drift response exercise",
        "ML system-design interview",
        "ML capstone assessment",
      ]),
    ],
  },
  {
    id: "deep-learning",
    order: 10,
    title: "Deep Learning",
    description:
      "Learn how neural networks work, train models with PyTorch, and understand attention and transformers.",
    duration: "5 weeks",
    difficulty: "Advanced",
    lessonIds: [],
    modules: [
      module("neural-networks", "Neural Networks", [
        "Perceptrons",
        "Activation functions",
        "Loss functions",
        "Gradient descent",
        "Backpropagation and optimizers",
      ]),
      module("pytorch", "PyTorch", [
        "Tensors",
        "Models and modules",
        "Datasets",
        "Training loops",
        "Evaluation",
      ]),
      module("dl-architectures", "Architectures", [
        "CNN concepts",
        "RNN concepts",
        "Attention",
        "Transformers",
      ]),
      module("dl-specializations", "NLP & Computer Vision", [
        "Text preprocessing and tokenization",
        "Sequence modeling",
        "Encoder and decoder architectures",
        "Image tensors and convolutions",
        "Image classification",
        "Object-detection concepts",
        "Transfer learning",
        "Multimodal foundations",
      ]),
      module("dl-production", "Deep Learning Production", [
        "GPU training workflows",
        "Mixed precision",
        "Distributed training concepts",
        "Checkpointing and reproducibility",
        "Model compression and quantization",
        "Inference optimization",
        "Deep-learning observability",
        "Deep-learning capstone",
      ]),
    ],
  },
  {
    id: "llm",
    order: 11,
    title: "Generative AI & LLM Engineering",
    description:
      "Build useful features with large language models. Check their answers, control safety, and manage speed and cost.",
    duration: "6 weeks",
    difficulty: "Advanced",
    lessonIds: [],
    modules: [
      module("llm-foundations", "LLM Foundations", [
        "Tokens and tokenization",
        "Embeddings",
        "Transformer architecture",
        "Attention and context windows",
        "Sampling concepts",
      ]),
      module("llm-apps", "LLM Applications", [
        "Prompting and system instructions",
        "Structured outputs",
        "Tool calling",
        "Streaming",
        "Model APIs",
      ]),
      module("llm-production", "Production LLMs", [
        "Evaluation",
        "Safety",
        "Caching",
        "Cost and latency",
        "Observability",
      ]),
    ],
  },
  {
    id: "rag",
    order: 12,
    title: "Retrieval-Augmented Generation",
    description:
      "Build RAG apps that find trusted information before answering. Add sources and check answer quality.",
    duration: "5 weeks",
    difficulty: "Advanced",
    lessonIds: [],
    modules: [
      module("rag-ingestion", "Ingestion", [
        "RAG fundamentals",
        "Document parsing",
        "Chunking",
        "Embeddings and metadata",
      ]),
      module("rag-retrieval", "Retrieval", [
        "Vector databases",
        "Similarity search",
        "Filtering",
        "Hybrid search",
        "Reranking",
      ]),
      module("rag-generation", "Grounded Generation", [
        "Prompt construction",
        "Citations",
        "Hallucination reduction",
        "RAG evaluation",
        "Production RAG",
      ]),
    ],
  },
  {
    id: "agents",
    order: 13,
    title: "AI Agents",
    description:
      "Build AI agents that use tools safely, remember their work, ask for approval, recover from errors, and get tested.",
    duration: "5 weeks",
    difficulty: "Advanced",
    lessonIds: [],
    modules: [
      module("agent-core", "Agent Foundations", [
        "Agents and tools",
        "Function calling",
        "Planning",
        "Memory concepts",
        "State and workflows",
      ]),
      module("agent-reliability", "Reliable Agents", [
        "Retries",
        "Human approval",
        "Guardrails",
        "Observability",
        "Agent evaluation",
        "Security",
      ]),
      module("agent-systems", "Agent Systems", [
        "Multi-agent concepts",
        "Research agent",
        "Coding assistant",
        "Support and workflow agents",
      ]),
    ],
  },
  {
    id: "full-stack-ai",
    order: 14,
    title: "Full-Stack AI Engineering",
    description:
      "Combine the frontend, backend, database, Python, RAG, and agent skills to build complete AI products.",
    duration: "6 weeks",
    difficulty: "Advanced",
    lessonIds: [],
    modules: [
      module("ai-integration", "AI Product Integration", [
        "Frontend streaming UX",
        "Typed AI APIs",
        "Authentication and ownership",
        "Data and vector architecture",
        "Async AI jobs",
      ]),
      module("ai-saas", "Production AI SaaS", [
        "Evaluation pipelines",
        "Feedback systems",
        "Cost controls",
        "Safety and permissions",
        "Monitoring and incident response",
      ]),
      module("ai-capstone", "Capstone", [
        "Architecture",
        "Milestones",
        "Testing",
        "Deployment",
        "Portfolio case study",
      ]),
    ],
  },
  {
    id: "devops",
    order: 15,
    title: "DevOps & Deployment",
    description:
      "Release and run apps with Linux, automatic checks, containers, cloud services, security, logs, and monitoring.",
    duration: "4 weeks",
    difficulty: "Advanced",
    lessonIds: [],
    modules: [
      module("delivery", "Software Delivery", [
        "Linux fundamentals",
        "Environment variables and secrets",
        "Git workflows",
        "CI/CD",
        "Docker and containers",
      ]),
      module("deployment", "Deployment", [
        "Cloud concepts",
        "Frontend and backend deployment",
        "Database deployment",
        "HTTPS and domains",
      ]),
      module("operations", "Operations", [
        "Logging and monitoring",
        "Performance",
        "Scaling",
        "Backup and recovery",
      ]),
      module("kubernetes", "Kubernetes", [
        "Kubernetes architecture",
        "Pods and workloads",
        "Services and ingress",
        "Configuration and secrets",
        "Health probes",
        "Requests and limits",
        "Autoscaling",
        "Stateful workloads",
        "Helm and package management",
        "Kubernetes security",
      ]),
      module("cloud-platforms", "Cloud Architecture", [
        "AWS, Azure and GCP foundations",
        "Identity and access management",
        "Virtual networks",
        "Compute and serverless",
        "Managed databases",
        "Object storage",
        "Cloud load balancing",
        "Infrastructure as code",
        "Cloud cost optimization",
        "Multi-account and multi-environment strategy",
      ]),
      module("sre-incidents", "SRE & Production Incidents", [
        "Metrics, logs and traces",
        "Alert design",
        "On-call and incident response",
        "CPU saturation incident",
        "Kubernetes crash-loop incident",
        "Broken deployment incident",
        "Replication lag incident",
        "Service timeout incident",
        "Disaster-recovery game day",
        "Production operations capstone",
      ]),
    ],
  },
  {
    id: "career",
    order: 16,
    title: "Interview & Job Preparation",
    description:
      "Turn your skills and projects into a strong portfolio, clear interview answers, and better job applications.",
    duration: "4 weeks",
    difficulty: "Advanced",
    lessonIds: [],
    modules: [
      module("technical-interviews", "Technical Interviews", [
        "JavaScript and TypeScript",
        "React",
        "Node and SQL",
        "System design",
        "Python and ML",
        "LLMs, RAG and agents",
      ]),
      module("framework-interviews", "Framework & Platform Interviews", [
        "React interviews",
        "Angular interviews",
        "Frontend architecture interviews",
        "Backend debugging interviews",
        "Database interviews",
        "DevOps and cloud interviews",
        "Production incident interviews",
      ]),
      module("senior-interviews", "Senior to Principal Interviews", [
        "System-design interviews",
        "Architecture trade-off interviews",
        "Technical strategy interviews",
        "Migration case studies",
        "Incident leadership interviews",
        "Cross-team influence stories",
        "Staff and principal mock loop",
      ]),
      module("career-assets", "Career Assets", [
        "Resume",
        "GitHub profile",
        "Portfolio case studies",
        "Project deep dives",
      ]),
      module("job-process", "Job Process", [
        "Behavioral interviews",
        "Mock interviews",
        "Applications",
        "Negotiation and growth plan",
      ]),
    ],
  },
];

export const totalCatalogTopics = curriculumPhases.reduce(
  (sum, phase) =>
    sum + phase.modules.reduce((count, item) => count + item.topics.length, 0),
  0,
);

export const getPhaseModules = (
  phase: CurriculumPhase,
  frontendPath: FrontendFrameworkPath | null,
) => {
  if (phase.id !== "frontend") return phase.modules;
  return phase.modules.filter(
    (item) =>
      item.track === "common" ||
      frontendPath === "both" ||
      item.track === frontendPath,
  );
};
