export type TopicKnowledge = {
  definition: string;
  importance: string;
  steps: string[];
  realWorld: string;
  example?: string;
  practice: string;
};
const k = (
  definition: string,
  importance: string,
  steps: string[],
  realWorld: string,
  practice: string,
  example?: string,
): TopicKnowledge => ({
  definition,
  importance,
  steps,
  realWorld,
  practice,
  example,
});

const topics: Record<string, TopicKnowledge> = {
  "orientation:How computers execute instructions": k(
    "A computer executes encoded instructions by fetching them from memory, decoding the requested operation, performing it, and storing the result.",
    "This model explains why programs need exact syntax, why memory affects performance, and why software cannot act on unstated intent.",
    [
      "Input and program data enter memory.",
      "The CPU fetches the next instruction.",
      "The control unit decodes it.",
      "The CPU calculates, compares, loads, or stores a value.",
      "The instruction pointer advances and the cycle repeats.",
    ],
    "When a calculator adds two prices, the characters you typed are parsed into numbers, loaded into memory, added by the processor, then formatted for the screen.",
    "Trace a three-line arithmetic program and record every value after each instruction.",
  ),
  "orientation:Hardware, memory and storage": k(
    "Hardware is the physical system. The CPU processes instructions, RAM holds active data, and persistent storage keeps files when power is removed.",
    "Developers use this distinction to diagnose slow applications, choose data structures, understand crashes, and estimate what can fit in memory.",
    [
      "Input devices encode data.",
      "Storage loads program files into RAM.",
      "The CPU reads instructions and values from memory.",
      "Output is sent to a display, network, or file.",
      "Saved results are written back to persistent storage.",
    ],
    "Opening a large photo loads compressed bytes from an SSD into RAM; the CPU or GPU decodes them into pixels; the display presents the result.",
    "Compare RAM and SSD by persistence, speed, capacity, cost, and typical developer use.",
  ),
  "orientation:Programs and algorithms": k(
    "An algorithm is a finite, ordered method for solving a class of problems. A program expresses algorithms and data in instructions a runtime can execute.",
    "Separating the solution method from syntax lets you reason, test, and improve before committing to a language.",
    [
      "Define the input and desired output.",
      "Split the transformation into unambiguous steps.",
      "Identify decisions and repetition.",
      "Test normal and edge cases by hand.",
      "Express the verified steps as code.",
    ],
    "A navigation app receives a start and destination, evaluates possible routes, scores time and constraints, and returns the best candidate.",
    "Write pseudocode that finds the least expensive item in a shopping list, including an empty-list case.",
  ),
  "orientation:Operating systems and files": k(
    "An operating system manages processes, memory, devices, users, permissions, and a hierarchical file system on behalf of applications.",
    "Code runs inside OS rules. Paths, permissions, processes, environment variables, and line endings directly affect development and deployment.",
    [
      "A path identifies a location in the file-system tree.",
      "The OS checks the current user and permissions.",
      "A program requests the file through a system call.",
      "The OS locates blocks on storage and returns bytes.",
      "The program interprets those bytes using an expected format.",
    ],
    "Saving a source file asks the OS to create or replace bytes at a path; Git later reads those bytes to calculate changes.",
    "Create a project folder tree on paper and write absolute and relative paths between three files.",
  ),
  "orientation:How the web works": k(
    "The web is a distributed information system where clients request resources identified by URLs and servers return HTTP responses.",
    "Every frontend, API, authentication flow, asset, and AI web product relies on this request-response foundation.",
    [
      "Parse the URL.",
      "Resolve the domain through DNS.",
      "Create a network connection, normally protected by TLS.",
      "Send an HTTP request.",
      "Receive and interpret the response.",
      "Fetch dependent assets and render the page.",
    ],
    "Opening an online shop causes the browser to request HTML, styles, scripts, images, and API data from one or more servers.",
    "Use the browser Network panel to identify the document request, its status, content type, and largest dependent resource.",
  ),
  "orientation:Client and server": k(
    "A client initiates communication to use a service; a server listens for requests, applies rules, accesses data, and sends responses.",
    "The boundary determines which logic users can inspect, which data must be protected, and where authorization must be enforced.",
    [
      "The client collects user intent.",
      "It validates basic interaction and sends a request.",
      "The server authenticates and authorizes the caller.",
      "Domain logic reads or changes data.",
      "The server returns a safe response.",
      "The client renders success or an error state.",
    ],
    "In mobile banking, the app can format a transfer form, but the bank server must verify identity, balance, limits, and ownership.",
    "Classify five responsibilities of a todo app as client, server, or shared, and justify each boundary.",
  ),
  "orientation:DNS, URLs and HTTP": k(
    "A URL identifies a resource, DNS maps a hostname to network addresses, and HTTP defines messages exchanged between clients and servers.",
    "Understanding these layers makes redirects, caching, API failures, cookies, HTTPS, and deployment much easier to debug.",
    [
      "Break the URL into scheme, host, port, path, query, and fragment.",
      "Resolve the host with DNS.",
      "Send an HTTP method, path, headers, and optional body.",
      "Read the response status, headers, and body.",
      "Apply caching, redirects, or content handling.",
    ],
    "A product search URL can encode filters in its query string, while the server returns JSON and cache headers for repeat requests.",
    "Annotate every part of https://shop.example.com:443/products?q=phone#reviews and design a matching GET request.",
  ),
  "orientation:Browsers and developer tools": k(
    "A browser fetches resources, parses HTML and CSS, executes JavaScript, builds render structures, handles input, and enforces web security boundaries.",
    "Developer tools reveal the actual DOM, computed styles, network traffic, storage, performance, accessibility tree, and runtime errors.",
    [
      "HTML becomes the DOM.",
      "CSS becomes the CSS object model.",
      "The browser combines them for layout and paint.",
      "JavaScript can update state and the DOM.",
      "DevTools exposes each stage for inspection.",
    ],
    "When a button looks wrong, inspect its element, matched rules, computed dimensions, event listeners, and accessible name rather than changing CSS blindly.",
    "Inspect one page and record a DOM property, overridden CSS rule, network request, console value, and local-storage entry.",
  ),
  "orientation:Terminal and file system": k(
    "A terminal is a text interface to a shell, which parses commands and asks the operating system to run programs or manipulate files.",
    "Build tools, Git, servers, tests, containers, and cloud systems are routinely controlled through command-line interfaces.",
    [
      "The prompt shows the current context.",
      "The shell parses a command and arguments.",
      "It resolves the executable using PATH.",
      "The process runs with the current directory and environment.",
      "An exit code and output report the result.",
    ],
    "Running npm test asks the shell to locate npm, npm reads package.json, launches the configured program, and returns success or failure.",
    "Create folders and files using safe commands, navigate with relative paths, and explain the difference between command, option, and argument.",
  ),
  "orientation:VS Code and extensions": k(
    "VS Code is an editor that combines text editing with language services, debugging, source control, tasks, and an integrated terminal.",
    "A disciplined editor setup provides fast feedback without hiding how the underlying compiler, formatter, linter, and debugger work.",
    [
      "Open the project folder, not isolated files.",
      "Select the workspace language and formatter settings.",
      "Use language diagnostics to inspect an error.",
      "Run the real project command in the terminal.",
      "Debug with breakpoints and inspect values.",
    ],
    "A TypeScript extension can display a type error immediately, while the project build remains the authoritative verification.",
    "Configure format-on-save for one workspace, trigger a lint error intentionally, and distinguish editor feedback from build output.",
  ),
  "orientation:Git and GitHub": k(
    "Git is a distributed version-control system that stores snapshots and history locally. GitHub hosts Git repositories and adds collaboration workflows.",
    "Version control makes changes reviewable, reversible, attributable, and safe to combine across developers.",
    [
      "Inspect changes in the working tree.",
      "Stage the exact changes for one logical unit.",
      "Commit the snapshot with an outcome-focused message.",
      "Fetch and integrate remote history.",
      "Push commits and collaborate through reviews.",
    ],
    "A feature branch can contain several commits, receive automated checks and peer review, then merge without emailing copies of files.",
    "Create a repository, change two files, stage only one, inspect the staged diff, commit it, and explain where the other change remains.",
  ),
  "orientation:npm and package management": k(
    "npm is a package manager and registry client for JavaScript projects. package.json declares scripts, dependencies, metadata, and package constraints.",
    "Modern applications depend on reproducible tools and libraries; careless dependency changes can create security, compatibility, and build risks.",
    [
      "A project declares a dependency range.",
      "npm resolves a concrete dependency graph.",
      "The lockfile records exact versions and integrity data.",
      "Packages are installed locally.",
      "Scripts run project-owned tools in a consistent context.",
    ],
    "A Vite project may use React at runtime and TypeScript, ESLint, and a test runner during development, all recorded for repeatable installation.",
    "Inspect package.json and classify every dependency as runtime or development; explain why the lockfile should be committed.",
  ),
  "orientation:Debugging mindset": k(
    "Debugging is the controlled process of reproducing a failure, gathering evidence, isolating its cause, correcting it, and preventing recurrence.",
    "Professional engineering depends more on reliable diagnosis than random changes or memorized fixes.",
    [
      "Write the expected and actual behavior.",
      "Reproduce the smallest failing case.",
      "Observe logs, state, network, and stack traces.",
      "Form one falsifiable hypothesis.",
      "Change one variable and rerun.",
      "Fix the cause and add a regression check.",
    ],
    "If a form silently fails, confirm the click event, inspect validation, watch the network request, read the response, and trace the resulting state update.",
    "Debug a deliberately broken function using a written hypothesis log; do not edit until you can state what evidence would disprove your hypothesis.",
  ),
  "web:HTML document structure": k(
    "An HTML document is a nested tree of semantic elements with metadata in head and user-facing content in body.",
    "Correct structure gives browsers, search engines, assistive technology, and developers a predictable document model.",
    [
      "Declare modern HTML with doctype.",
      "Set the document language.",
      "Add character encoding and viewport metadata.",
      "Give the page a unique title.",
      "Place one main content region inside body.",
      "Validate nesting and heading order.",
    ],
    "A news article uses header, nav, main, article, headings, time, and footer to communicate meaning independently of visual styling.",
    "Build and validate a complete article document that remains understandable with CSS disabled.",
    '<!doctype html>\n<html lang="en">\n<head><meta charset="utf-8"><title>Article</title></head>\n<body><main><article><h1>Title</h1><p>Story</p></article></main></body>\n</html>',
  ),
  "web:Text, links and images": k(
    "HTML text elements express hierarchy and emphasis, links identify navigable destinations, and images embed visual content with alternative text when meaningful.",
    "Clear structure and link purpose improve scanning, keyboard navigation, search indexing, and nonvisual access.",
    [
      "Choose headings by document hierarchy.",
      "Group prose into paragraphs and meaningful lists.",
      "Use an anchor for navigation and a button for actions.",
      "Write link text that makes sense out of context.",
      "Provide useful alt text or empty alt for decoration.",
    ],
    "A recipe page uses headings for sections, a list for ingredients, descriptive links for related recipes, and alt text describing an instructional photo.",
    "Audit a content page for skipped headings, vague 'click here' links, and redundant image alt text.",
  ),
  "web:Lists and tables": k(
    "Lists group related items with inherent order or without it; tables represent relationships between row and column headers and data cells.",
    "Using the correct structure lets browsers and assistive technology communicate relationships that visual spacing alone cannot preserve.",
    [
      "Decide whether order changes meaning.",
      "Use ul or ol with li children.",
      "Use tables only for genuinely tabular data.",
      "Add a caption and header cells.",
      "Associate complex headers using scope where needed.",
      "Test at narrow widths.",
    ],
    "A comparison of subscription plans belongs in a table; navigation items belong in a list; arranging a page into columns does not justify a table.",
    "Create an accessible monthly-expenses table with caption, column headings, row headings, and a total.",
  ),
  "web:Forms and validation": k(
    "A form collects structured user input through labeled controls and submits it for processing. Validation checks whether input satisfies defined constraints.",
    "Forms power login, search, checkout, settings, and data entry, and must work with keyboards, assistive technology, errors, and unreliable networks.",
    [
      "Choose the correct input type and name.",
      "Connect every control to a visible label.",
      "Group related controls with fieldset and legend.",
      "Apply useful client constraints.",
      "Validate again on the server.",
      "Place actionable errors near controls and move focus appropriately.",
    ],
    "A checkout form can catch a missing postal code in the browser, but the server still verifies every field before creating an order.",
    "Build a contact form that communicates required fields, invalid email, submission progress, server error, and success without relying on color.",
  ),
  "web:Semantic and accessible HTML": k(
    "Semantic HTML uses native elements according to their meaning and interaction behavior, forming the accessibility foundation before ARIA or JavaScript.",
    "Native landmarks and controls provide keyboard behavior, roles, names, and states with less code and fewer accessibility failures.",
    [
      "Identify the content or action purpose.",
      "Choose the closest native element.",
      "Provide a clear accessible name.",
      "Preserve logical source and focus order.",
      "Add ARIA only when native semantics are insufficient.",
      "Test with keyboard and an accessibility tree.",
    ],
    "A button activates an in-page action; an anchor navigates to a resource. Styling a div to look clickable does not give it those behaviors.",
    "Replace nonsemantic controls in a sample interface and verify Tab, Enter, Space, focus visibility, role, name, and state.",
  ),
  "web:Metadata and SEO": k(
    "Document metadata describes the page to browsers, search engines, link previews, and other consumers without appearing as primary page content.",
    "Accurate titles, descriptions, canonical URLs, language, and structured content improve discovery and prevent confusing or duplicate results.",
    [
      "Write a unique descriptive title.",
      "Add a concise page-specific description.",
      "Set language, encoding, and viewport.",
      "Choose a canonical URL when duplicates exist.",
      "Ensure important content exists in semantic HTML.",
      "Measure with search and sharing tools rather than keyword stuffing.",
    ],
    "A product page title names the product and store, while its description summarizes the benefit accurately instead of repeating unrelated keywords.",
    "Create metadata for a portfolio case study and evaluate how it would appear in a search result and shared link.",
  ),
  "web:CSS foundations and the box model": k(
    "CSS matches elements and applies declarations through the cascade. The box model represents content surrounded by padding, border, and margin.",
    "Predictable sizing and cascade reasoning prevent fragile layouts and endless specificity overrides.",
    [
      "Select the intended element.",
      "Resolve competing declarations through cascade order and specificity.",
      "Calculate content, padding, border, and margin.",
      "Use border-box for intuitive dimensions.",
      "Inspect computed styles instead of guessing.",
    ],
    "A 320px border-box card keeps its padding and border inside 320px, while the same content-box card becomes wider than declared.",
    "Calculate both box models by hand, then verify them in DevTools.",
    "*,*::before,*::after{box-sizing:border-box}.card{width:20rem;padding:1rem;border:1px solid}",
  ),
  "web:Cascade and specificity": k(
    "The cascade selects a winning declaration using relevance, origin, importance, layers, specificity, scoping proximity, and source order.",
    "Understanding the full cascade lets teams design maintainable CSS instead of escalating selectors and !important rules.",
    [
      "Discard declarations that do not match.",
      "Compare origin and importance.",
      "Compare cascade layers.",
      "Compare selector specificity.",
      "Use scoping proximity where applicable.",
      "Use source order only after earlier criteria tie.",
    ],
    "A low-specificity utility in a later layer can intentionally override component defaults without deeply nested selectors.",
    "Predict five conflicting declarations, verify the winner in computed styles, and explain each discarded rule.",
  ),
  "web:Typography, colors and units": k(
    "Typography controls readable text relationships; color communicates hierarchy and state; CSS units express fixed, font-relative, container-relative, or viewport-relative dimensions.",
    "Readable type, adaptable units, and sufficient contrast determine whether content works across devices, zoom levels, and visual abilities.",
    [
      "Choose a readable base font and line height.",
      "Create a restrained type scale.",
      "Use rem for user-scalable text and spacing.",
      "Use relative widths and deliberate maximum line length.",
      "Check color contrast in every state.",
      "Verify at 200% zoom and high contrast.",
    ],
    "An article may use a 65-character line length and rem-based spacing so browser font preferences scale the entire rhythm.",
    "Create light and dark text tokens, test normal/muted/link/button contrast, and resize text without clipping.",
  ),
  "web:Display and positioning": k(
    "Display determines an element’s formatting behavior; positioning controls how its box participates in normal flow and where offsets are resolved.",
    "Misunderstanding flow, containing blocks, and stacking contexts causes overlap, disappearing content, and fragile absolute coordinates.",
    [
      "Start with normal document flow.",
      "Choose block, inline, flex, or grid based on layout relationships.",
      "Use relative positioning to establish an offset reference only when needed.",
      "Use absolute for contained overlays, fixed for viewport controls, and sticky for scroll thresholds.",
      "Inspect stacking contexts before increasing z-index.",
    ],
    "A tooltip can be absolutely positioned relative to its trigger container, while the article text remains in normal flow.",
    "Build a sticky header and contained badge, then explain each element’s containing block and stacking context.",
  ),
  "web:Flexbox": k(
    "Flexbox is a one-dimensional layout model that distributes items along a main axis and aligns them along a cross axis.",
    "It handles navigation rows, toolbars, card internals, centering, and flexible groups without manual margins or positioning.",
    [
      "Choose the main direction.",
      "Identify available free space.",
      "Set wrapping behavior.",
      "Distribute with justify-content.",
      "Align with align-items or align-self.",
      "Control growth and shrink with the flex shorthand.",
    ],
    "A toolbar keeps its title flexible while action buttons retain usable sizes and wrap on narrow screens.",
    "Build a responsive toolbar and explain why min-width:0 may be required for the flexible text item.",
    ".toolbar{display:flex;align-items:center;gap:.75rem}.title{flex:1;min-width:0}",
  ),
  "web:Grid": k(
    "CSS Grid is a two-dimensional layout model that defines rows and columns, places items into grid areas, and distributes track space.",
    "Grid is effective for page regions, dashboards, galleries, and layouts where rows and columns must coordinate.",
    [
      "Define explicit or responsive tracks.",
      "Choose gaps between tracks.",
      "Place items by natural order, line, or named area.",
      "Use minmax to state lower and upper bounds.",
      "Let auto-placement handle repeated content.",
      "Collapse to simpler tracks at constrained widths.",
    ],
    "A card gallery can create as many columns as fit while preventing cards from becoming narrower than their readable minimum.",
    "Build a gallery using repeat(auto-fit,minmax(...)) and test with one, five, and twenty cards.",
    ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(16rem,1fr));gap:1rem}",
  ),
  "web:Responsive design": k(
    "Responsive design lets content and interaction adapt to available space, input method, text size, and user preferences.",
    "Users do not experience fixed device categories; layouts must survive narrow screens, zoom, long text, touch, keyboards, and reduced motion.",
    [
      "Begin with a single-column content order.",
      "Use fluid sizes with sensible min/max bounds.",
      "Add breakpoints where content needs them.",
      "Avoid fixed heights for text containers.",
      "Provide 44px touch targets.",
      "Test keyboard, zoom, rotation, and reduced motion.",
    ],
    "A dashboard turns four columns into two and then one when cards can no longer preserve readable widths.",
    "Test a page at 320, 375, 768, 1280, and 1440px and document content-driven breakpoint decisions.",
  ),
  "web:Transitions and animation": k(
    "A transition interpolates a property between states; an animation runs named keyframes over time.",
    "Purposeful motion can explain change, continuity, hierarchy, and feedback, while excessive motion harms comprehension and accessibility.",
    [
      "Identify the state change motion should clarify.",
      "Animate composited properties such as transform and opacity when possible.",
      "Keep interaction transitions brief.",
      "Avoid animating layout-heavy properties at scale.",
      "Respect prefers-reduced-motion.",
      "Never delay essential feedback for decoration.",
    ],
    "A menu can fade and translate slightly to show its origin, while reduced-motion users receive an immediate state change.",
    "Create a focus/hover transition and an entrance animation with an equivalent reduced-motion rule.",
  ),
  "web:CSS architecture": k(
    "CSS architecture organizes tokens, foundations, components, utilities, states, and overrides so visual rules remain predictable as a product grows.",
    "Without boundaries, selectors become tightly coupled, overrides multiply, and changing one component causes unrelated regressions.",
    [
      "Define semantic design tokens.",
      "Set global reset and element defaults.",
      "Keep component selectors shallow.",
      "Represent variants and states explicitly.",
      "Control override order with layers or documented source order.",
      "Remove unused rules and test visual states.",
    ],
    "A button component uses shared surface, text, focus, disabled, and danger tokens rather than repeating raw colors across features.",
    "Refactor duplicated card and button rules into tokens and components without changing computed output.",
  ),
  "web:Personal page": k(
    "A personal page is a small semantic website that introduces one person, their interests, and contact or profile links.",
    "It is the first complete exercise in content hierarchy, accessible navigation, responsive layout, and publishing.",
    [
      "Define the audience and page goal.",
      "Outline header, main sections, and footer.",
      "Write semantic HTML before styling.",
      "Add responsive typography and spacing.",
      "Audit links, headings, contrast, and keyboard access.",
      "Publish and verify the deployed URL.",
    ],
    "A student profile can include an introduction, current learning goals, selected work, and a contact link without exposing private information.",
    "Build the page without a framework and write a short accessibility and responsive self-review.",
  ),
  "web:Landing page": k(
    "A landing page focuses a visitor on one proposition and a primary action using clear information hierarchy and supporting evidence.",
    "It combines content design, semantic structure, responsive composition, performance, and ethical conversion design.",
    [
      "Define audience, problem, promise, and action.",
      "Order sections from understanding to evidence to decision.",
      "Make the primary action descriptive.",
      "Build mobile-first layout.",
      "Optimize images and fonts.",
      "Test comprehension, accessibility, and performance.",
    ],
    "A course landing page explains who it helps, what outcome it supports, how it works, evidence, frequently asked questions, and enrollment action.",
    "Build two responsive variants and compare them using a written usability checklist rather than visual preference alone.",
  ),
  "web:Responsive portfolio": k(
    "A responsive portfolio presents selected evidence of skill through accessible case studies that adapt across screen and input conditions.",
    "Hiring reviewers need concise proof of decisions, implementation, verification, and impact—not only screenshots or technology lists.",
    [
      "Choose a small set of relevant projects.",
      "Write problem, constraints, role, decisions, and outcomes.",
      "Build semantic case-study pages.",
      "Add responsive media and navigation.",
      "Measure accessibility and performance.",
      "Test every external link and contact path.",
    ],
    "A search-dashboard case study explains debouncing, cancellation, cache decisions, accessibility tests, and measured latency improvements.",
    "Create one complete case study with architecture diagram, trade-off, test evidence, and a mobile layout.",
  ),
  "web:Business website": k(
    "A business website communicates services, credibility, location or availability, and clear next actions while supporting maintainable content and operations.",
    "Real client work adds content ownership, SEO, privacy, analytics, performance budgets, forms, and long-term maintenance constraints.",
    [
      "Interview stakeholders and define measurable goals.",
      "Create a sitemap and content model.",
      "Prototype key user journeys.",
      "Build reusable accessible components.",
      "Implement form privacy and abuse controls.",
      "Measure performance and establish an update process.",
    ],
    "A local clinic site must make services and contact options easy to find while protecting form data and remaining usable on slow mobile networks.",
    "Produce a requirements brief, sitemap, responsive implementation, test checklist, deployment plan, and maintenance handoff.",
  ),
  "javascript:Variables, values, and functions": k(
    "Values are data; variables bind names to values; functions package behavior that receives inputs and can return an output.",
    "These are the smallest building blocks of JavaScript programs and determine how state and behavior are expressed.",
    [
      "Create a value.",
      "Bind it with const or let.",
      "Pass values into parameters.",
      "Execute the function body.",
      "Return a result to the caller.",
    ],
    "A checkout function receives price and quantity and returns a subtotal that another function can tax.",
    "Write calculateSubtotal(price, quantity), validate its inputs, and test zero, decimal, and negative cases.",
    "function subtotal(price, quantity) {\n  if (price < 0 || quantity < 0) throw new RangeError('positive values required');\n  return price * quantity;\n}",
  ),
  "javascript:Types and conversion": k(
    "A JavaScript type describes the operations and behavior of a value. Conversion creates a value of another type, explicitly or through coercion.",
    "Inputs from forms, URLs, storage, and APIs often arrive with different types than application logic expects.",
    [
      "Inspect the source value and its type.",
      "Choose the intended target type.",
      "Convert explicitly with Number, String, or Boolean.",
      "Check invalid results such as NaN.",
      "Keep internal domain values consistently typed.",
    ],
    "An age input begins as the string '21'; numeric comparison should use a validated number instead of relying on coercion.",
    "Parse three user inputs safely and explain the difference between Number('') and parseInt('').",
    "const parsed = Number(raw);\nif (!Number.isFinite(parsed)) throw new TypeError('Valid number required');",
  ),
  "javascript:Operators and expressions": k(
    "An expression produces a value. Operators combine, compare, assign, or transform operands according to precedence and type rules.",
    "Expressions encode calculations and decisions; precedence or coercion mistakes can silently change program behavior.",
    [
      "Identify each operand type.",
      "Apply parentheses where grouping matters.",
      "Evaluate higher-precedence operations first.",
      "Use strict equality for intentional comparison.",
      "Store or return the resulting value.",
    ],
    "A cart expression combines item prices, discounts, tax, and shipping while comparisons decide whether free shipping applies.",
    "Predict ten mixed arithmetic, comparison, logical, and nullish-coalescing expressions before running them.",
    "const displayName = user.nickname ?? user.fullName;\nconst eligible = total >= 500 && account.active;",
  ),
  "javascript:Conditions and switch": k(
    "Conditional control flow selects which statements execute based on boolean decisions. switch compares one discriminant against multiple cases.",
    "Applications use conditions for permissions, validation, UI state, pricing rules, and error handling.",
    [
      "List mutually exclusive states.",
      "Write the most specific condition first.",
      "Handle the expected branches.",
      "Provide an explicit fallback.",
      "Test boundaries and impossible states.",
    ],
    "An order can be pending, paid, shipped, delivered, or cancelled; each state permits different actions.",
    "Implement an order-action function and test unknown status, cancellation, and delivered states.",
    "switch (order.status) {\n  case 'paid': return ['cancel', 'ship'];\n  case 'shipped': return ['track'];\n  default: return [];\n}",
  ),
  "javascript:Loops": k(
    "A loop repeats a block while traversing data or while a condition remains true.",
    "Loops process lists, retry bounded work, generate output, and implement algorithms, but unbounded loops can freeze the main thread.",
    [
      "Define the initial state.",
      "Check the continuation condition.",
      "Execute one iteration.",
      "Update progress toward termination.",
      "Return or collect the final result.",
    ],
    "A receipt loop visits each cart item, validates its quantity, and accumulates a total.",
    "Process nested order data, skip cancelled items, stop at an invalid record, and explain termination.",
    "let total = 0;\nfor (const item of items) {\n  if (!item.active) continue;\n  total += item.price * item.quantity;\n}",
  ),
  "javascript:Scope and hoisting": k(
    "Scope determines where a binding can be accessed. Hoisting describes how declarations are registered before execution, including the temporal dead zone for let and const.",
    "Correct scope prevents name collisions, accidental globals, stale data, and incorrect assumptions about declaration timing.",
    [
      "Identify global, module, function, and block boundaries.",
      "Locate the declaration for each identifier.",
      "Check whether execution has initialized it.",
      "Prefer the narrowest useful scope.",
      "Avoid depending on declaration-order surprises.",
    ],
    "A loop counter declared with let exists only in its block, while a module-level configuration remains private to that module.",
    "Trace five identifiers through nested blocks and functions; identify one temporal-dead-zone error.",
    "const taxRate = 0.18;\nfunction total(price) {\n  const tax = price * taxRate;\n  return price + tax;\n}",
  ),
  "javascript:Arrays": k(
    "An array is an ordered, zero-indexed collection with a dynamic length and built-in methods for iteration and transformation.",
    "Arrays represent search results, messages, cart items, measurements, and any sequence where order or repeated processing matters.",
    [
      "Create or receive the sequence.",
      "Read items by index or iteration.",
      "Choose mutation or a new-array transformation deliberately.",
      "Handle empty and sparse data.",
      "Return a predictable result.",
    ],
    "A product page filters unavailable items, sorts by price, and maps each product into display data.",
    "Implement unique even-number extraction without mutating the input; test empty, negative, duplicate, and large arrays.",
    "const visible = products\n  .filter(product => product.inStock)\n  .map(product => ({ id: product.id, label: product.name }));",
  ),
  "javascript:Objects": k(
    "An object groups keyed properties and behavior, with keys resolved through its own properties and prototype chain.",
    "Objects model domain entities, configuration, API payloads, component props, and lookup structures.",
    [
      "Choose stable property names.",
      "Create the object with required fields.",
      "Read with dot or bracket notation.",
      "Update immutably when state history matters.",
      "Validate external objects before trusting them.",
    ],
    "A user object can group identity, preferences, and status while excluding secrets from data sent to the browser.",
    "Normalize an API user object into a safe public shape and handle missing optional values.",
    "const publicUser = {\n  id: raw.id,\n  name: raw.name.trim(),\n  avatarUrl: raw.avatarUrl ?? null\n};",
  ),
  "javascript:Destructuring": k(
    "Destructuring extracts array positions or object properties into bindings using a pattern.",
    "It makes expected input shape visible and supports defaults, renaming, rest collection, and concise parameter handling.",
    [
      "Match the pattern to the source shape.",
      "Extract only needed values.",
      "Rename ambiguous properties.",
      "Use defaults for undefined values.",
      "Avoid deeply nested patterns that hide validation.",
    ],
    "A component extracts title and status from props while collecting remaining HTML attributes separately.",
    "Destructure a nested API response with safe defaults, then rewrite it plainly and compare readability.",
    "const { title, status = 'draft', ...metadata } = article;\nconst [first, ...remaining] = results;",
  ),
  "javascript:Spread and rest": k(
    "Spread expands iterable values or object properties; rest collects remaining arguments, elements, or properties into one value.",
    "They support immutable updates, composition, variadic functions, and separating known from additional data.",
    [
      "Identify whether syntax appears in an expression or pattern.",
      "Spread shallow values into a new container.",
      "Rest remaining values into one binding.",
      "Remember nested references remain shared.",
      "Avoid spreading huge iterables unnecessarily.",
    ],
    "A settings update creates a new object with old properties and one override, allowing state change detection by reference.",
    "Update a nested profile immutably and prove which nested references changed.",
    "const next = {\n  ...profile,\n  preferences: { ...profile.preferences, theme: 'dark' }\n};",
  ),
  "javascript:Map and Set": k(
    "Map stores key-value pairs with keys of any type; Set stores unique values using SameValueZero equality.",
    "They provide clear semantics for caches, indexes, membership tests, deduplication, and graph relationships.",
    [
      "Choose Map for key-to-value lookup or Set for membership.",
      "Insert with set or add.",
      "Query with get or has.",
      "Iterate in insertion order.",
      "Delete entries or clear lifecycle-bound data.",
    ],
    "A permission Set answers whether a user has a capability; a Map indexes products by ID without repeatedly scanning an array.",
    "Build a word-frequency Map and a unique-word Set; explain time and memory trade-offs.",
    "const counts = new Map();\nfor (const word of words) counts.set(word, (counts.get(word) ?? 0) + 1);",
  ),
  "javascript:Higher-order functions": k(
    "A higher-order function receives a function, returns a function, or both, allowing behavior to be composed and configured.",
    "Array methods, event handlers, middleware, retries, memoization, and functional pipelines depend on treating functions as values.",
    [
      "Define the behavior contract.",
      "Pass a callback or configuration.",
      "Invoke it at the correct time with documented arguments.",
      "Return or combine its result.",
      "Preserve error and async behavior intentionally.",
    ],
    "A retry wrapper accepts an asynchronous operation and returns a new function that adds bounded retry behavior.",
    "Implement once(fn) so only the first call executes fn and later calls return the stored result.",
    "const withLogging = fn => (...args) => {\n  console.log('calling', fn.name);\n  return fn(...args);\n};",
  ),
  "javascript:Closures": k(
    "A closure is a function together with access to bindings in the lexical environment where it was created.",
    "Closures power private state, callbacks, factories, memoization, event handlers, and most module patterns.",
    [
      "Create an outer function and local binding.",
      "Create an inner function that references the binding.",
      "Return or pass the inner function.",
      "The outer call finishes, but referenced bindings remain reachable.",
      "Each outer call creates an independent environment.",
    ],
    "A createCounter factory returns increment and read methods that share private count state without a global variable.",
    "Build a rate-limit counter with private state and explain its lifecycle and memory retention.",
    "function createCounter() {\n  let count = 0;\n  return () => ++count;\n}",
  ),
  "javascript:Recursion": k(
    "Recursion solves a problem by calling the same function on a smaller subproblem until a base case stops further calls.",
    "Recursive structure naturally matches trees, nested data, divide-and-conquer algorithms, and backtracking.",
    [
      "Define the base case.",
      "Reduce the input toward that case.",
      "Call the function on the smaller input.",
      "Combine the returned result.",
      "Estimate call depth and consider iteration for deep data.",
    ],
    "A file-tree renderer processes one folder, then recursively processes each child folder.",
    "Recursively total values in nested arrays, then implement an iterative version and compare stack risk.",
    "function sumTree(node) {\n  if (typeof node === 'number') return node;\n  return node.reduce((sum, child) => sum + sumTree(child), 0);\n}",
  ),
  "javascript:DOM": k(
    "The Document Object Model is the browser’s object-tree representation of an HTML document, exposed to JavaScript for reading and controlled updates.",
    "Interactive web interfaces use the DOM to reflect state, manage focus, validate input, and respond to user or network events.",
    [
      "Parse HTML into nodes.",
      "Select the smallest stable target.",
      "Read or update properties and attributes.",
      "Insert, move, or remove nodes deliberately.",
      "Verify accessibility and avoid unsafe HTML injection.",
    ],
    "A filter form updates a results count and list while preserving the focused control and announcing changes when needed.",
    "Build a list renderer using createElement and textContent; never concatenate untrusted HTML.",
    "const item = document.createElement('li');\nitem.textContent = userProvidedLabel;\nlist.append(item);",
  ),
  "javascript:Events": k(
    "An event is an object describing something that happened. The browser dispatches it through capture, target, and bubble phases to registered listeners.",
    "Events connect user input, browser lifecycle, media, network, and custom application behavior to code.",
    [
      "Register a listener on an appropriate stable element.",
      "The browser creates and dispatches an event.",
      "Capture listeners run toward the target.",
      "Target and bubble listeners run outward.",
      "The handler reads event data and updates state.",
      "Remove lifecycle-bound listeners when finished.",
    ],
    "A table uses one click listener on its container and event.target.closest to handle actions for dynamically added rows.",
    "Implement event delegation for a todo list and prove keyboard activation still works.",
    "list.addEventListener('click', event => {\n  const button = event.target.closest('button[data-id]');\n  if (button) removeItem(button.dataset.id);\n});",
  ),
  "javascript:Forms and validation": k(
    "JavaScript form handling reads structured FormData, coordinates client validation and submission state, and communicates server results accessibly.",
    "It improves feedback and resilience, but server-side validation remains mandatory because client code is untrusted.",
    [
      "Listen to the form submit event.",
      "Use native constraints before custom rules.",
      "Read named controls with FormData.",
      "Disable duplicate submission while pending.",
      "Handle field and form errors.",
      "Restore focus and communicate success.",
    ],
    "A signup form checks password confirmation locally, submits once, then maps server validation errors to the related fields.",
    "Build an accessible async form with pending, validation, network failure, and success states.",
    "form.addEventListener('submit', async event => {\n  event.preventDefault();\n  if (!form.reportValidity()) return;\n  await submit(new FormData(form));\n});",
  ),
  "javascript:Modules": k(
    "An ECMAScript module is a file with explicit imports and exports, evaluated once with its own top-level scope.",
    "Modules create maintainable boundaries, enable static dependency analysis, and support bundling and code splitting.",
    [
      "Export a focused public API.",
      "Import it using a stable path.",
      "The loader resolves the dependency graph.",
      "Modules are instantiated and evaluated in dependency order.",
      "Consumers use live imported bindings.",
    ],
    "A cart module exports addItem and calculateTotal while keeping its internal normalization helper private.",
    "Split a small application into domain, data, and UI modules without circular dependencies.",
    "export function calculateTotal(items) {\n  return items.reduce((sum, item) => sum + item.price, 0);\n}",
  ),
  "javascript:Web storage": k(
    "Web Storage provides origin-scoped string key-value stores: localStorage persists across sessions and sessionStorage lasts for a tab session.",
    "It supports small local preferences and prototypes, but is synchronous, quota-limited, and accessible to same-origin scripts.",
    [
      "Choose local or session lifetime.",
      "Serialize a versioned non-sensitive value.",
      "Write behind a repository boundary.",
      "Parse unknown data defensively.",
      "Recover from corruption or quota errors.",
      "Never store secrets or pretend it is secure authentication.",
    ],
    "A learning prototype stores a profile-scoped progress document locally and can later replace the repository with an API.",
    "Create a versioned preferences adapter with validation, defaults, and a corrupted-JSON test.",
    "const raw = localStorage.getItem(key);\nconst value = raw ? safeParse(raw) : defaults;",
  ),
  "javascript:Accessibility with JavaScript": k(
    "Accessible JavaScript preserves semantic behavior and manages dynamic names, states, focus, announcements, and keyboard interaction when native HTML alone is insufficient.",
    "Dynamic interfaces can visually work while becoming unusable to keyboard or screen-reader users if updates are not communicated.",
    [
      "Use a native control first.",
      "Keep accessible name and state synchronized.",
      "Move focus only when context changes require it.",
      "Return focus when dialogs close.",
      "Announce important asynchronous results.",
      "Test keyboard and accessibility-tree output.",
    ],
    "A modal traps interaction appropriately, labels its title, closes with Escape, and returns focus to the button that opened it.",
    "Implement an accessible disclosure and modal, then test without a mouse.",
    "button.setAttribute('aria-expanded', String(open));\npanel.hidden = !open;",
  ),
  "javascript:Promises": k(
    "A Promise represents the eventual fulfillment or rejection of an asynchronous operation and schedules reactions as microtasks.",
    "Promises make async composition, error propagation, concurrency, and cleanup more structured than nested callbacks.",
    [
      "Create or receive a pending promise.",
      "The operation settles it exactly once.",
      "Fulfillment handlers receive the value.",
      "Rejection handlers receive the reason.",
      "then, catch, and finally create new promises.",
      "Unhandled rejection must be prevented or observed.",
    ],
    "A product request resolves with parsed data or rejects with an error that the UI turns into a retry state.",
    "Combine independent requests with Promise.all and explain fast rejection versus allSettled.",
    "fetch('/api/products')\n  .then(response => { if (!response.ok) throw new Error(String(response.status)); return response.json(); })\n  .catch(showError);",
  ),
  "javascript:Async and await": k(
    "async functions always return promises; await pauses that function’s continuation until a promise settles without blocking the JavaScript thread.",
    "The syntax makes dependent asynchronous steps readable while retaining promise error and concurrency semantics.",
    [
      "Call an async function and receive a promise.",
      "Execution runs synchronously until await.",
      "The function yields to the caller.",
      "The awaited result schedules a continuation microtask.",
      "Execution resumes or throws the rejection.",
      "The returned promise settles with the final outcome.",
    ],
    "A checkout first creates an order, then awaits payment confirmation, while independent recommendation requests run concurrently.",
    "Refactor sequential independent awaits into safe concurrency and add try/catch/finally UI cleanup.",
    "async function load() {\n  const [user, orders] = await Promise.all([getUser(), getOrders()]);\n  return { user, orders };\n}",
  ),
  "javascript:Fetch and HTTP APIs": k(
    "fetch sends an HTTP request and resolves to a Response once headers arrive; HTTP error statuses do not automatically reject the promise.",
    "Web apps depend on APIs, so code must handle encoding, status, parsing, cancellation, timeouts, and security deliberately.",
    [
      "Build a URL, method, headers, and optional body.",
      "Send with fetch and an AbortSignal.",
      "Check response.ok or status.",
      "Parse the body once using the declared media type.",
      "Validate the decoded data.",
      "Render success, empty, or actionable error state.",
    ],
    "A search UI cancels the previous request when the query changes so a slow old response cannot replace newer results.",
    "Implement a cancellable JSON request helper with status checks and validation.",
    "const response = await fetch(url,{signal});\nif (!response.ok) throw new Error(`HTTP ${response.status}`);\nconst data = await response.json();",
  ),
  "javascript:Event loop": k(
    "The event loop coordinates the call stack, host operations, task queues, microtasks, and rendering so asynchronous callbacks run when JavaScript is ready.",
    "It explains output order, responsiveness, timer behavior, rendering delays, and race conditions in browser applications.",
    [
      "Run the current synchronous stack to completion.",
      "Drain queued microtasks.",
      "Allow rendering when the browser chooses.",
      "Run the next eligible task.",
      "Repeat while work exists.",
    ],
    "A resolved promise callback runs before a zero-delay timer because microtasks drain before the next task.",
    "Predict mixed synchronous, promise, timer, and rendering order; then verify and explain every transition.",
    "console.log('A');\nsetTimeout(()=>console.log('B'),0);\nPromise.resolve().then(()=>console.log('C'));\nconsole.log('D'); // A D C B",
  ),
  "javascript:Call stack": k(
    "The call stack is a last-in, first-out structure of execution frames that records active functions, local bindings, and return positions.",
    "Stack traces, recursion limits, synchronous blocking, and error locations all depend on understanding active call frames.",
    [
      "Push the script frame.",
      "Push a frame when calling a function.",
      "Execute its statements and nested calls.",
      "Pop the frame when it returns or throws.",
      "Resume the caller at its saved position.",
    ],
    "calculateInvoice calls calculateLine repeatedly; an error stack shows the chain of active calls that led to invalid data.",
    "Draw the stack for three nested calls and identify the frame holding each local variable.",
    "function first(){ second(); }\nfunction second(){ third(); }\nfunction third(){ throw new Error('trace me'); }",
  ),
  "javascript:Cancellation and errors": k(
    "Cancellation asks ongoing work to stop when its result is no longer useful; error handling turns expected failures into explicit outcomes while preserving unexpected diagnostics.",
    "Without cancellation and disciplined errors, stale requests waste resources, race with current state, and leave interfaces inconsistent.",
    [
      "Create an AbortController for one operation.",
      "Pass its signal through every supported layer.",
      "Abort when work becomes irrelevant.",
      "Distinguish cancellation from operational failure.",
      "Clean up in finally.",
      "Show users an actionable state without exposing secrets.",
    ],
    "Changing search text aborts the old request; navigating away aborts page work; neither should display a frightening error toast.",
    "Build a latest-request-wins search flow and test slow, aborted, HTTP-error, invalid-JSON, and successful cases.",
    "const controller = new AbortController();\ntry { await fetch(url,{signal:controller.signal}); }\ncatch (error) { if (error.name !== 'AbortError') throw error; }",
  ),
  "javascript:Prototypes and classes": k(
    "Objects can delegate property lookup through a prototype chain. Class syntax defines constructor and prototype methods over that mechanism.",
    "Libraries, built-in objects, inheritance, method sharing, and many debugging surprises depend on prototype lookup.",
    [
      "Read an own property first.",
      "If absent, follow the internal prototype link.",
      "Continue until found or null.",
      "A class constructor initializes own state.",
      "Class methods live on the prototype and are shared.",
    ],
    "Thousands of User instances can share one displayName method instead of allocating a new function on every object.",
    "Implement the same model with constructor functions and class syntax, then inspect own keys and prototype methods.",
    "class Counter {\n  #value = 0;\n  increment(){ return ++this.#value; }\n}",
  ),
  "javascript:OOP and functional programming": k(
    "Object-oriented programming organizes state and behavior around collaborating objects; functional programming emphasizes value transformations, composition, and controlled effects.",
    "Both paradigms offer useful tools, and professional code chooses based on domain behavior, change patterns, and testability rather than ideology.",
    [
      "Identify domain state and operations.",
      "Choose encapsulated objects for stateful identity or functions for transformations.",
      "Keep side effects at explicit boundaries.",
      "Compose small public contracts.",
      "Test observable behavior, not internal style.",
    ],
    "An Order entity can enforce lifecycle rules while pure functions calculate totals and taxes.",
    "Model the same cart using a class and pure reducer; compare invariants, mutation, testing, and extension.",
    "const nextCart = (cart, action) =>\n  action.type === 'add' ? [...cart, action.item] : cart;",
  ),
  "javascript:Design patterns": k(
    "A design pattern is a named, reusable approach to a recurring design problem, including its intent, forces, structure, and trade-offs.",
    "Patterns improve communication and design options, but applying them without a real problem creates indirection.",
    [
      "Name the recurring problem.",
      "List constraints and forces.",
      "Select the smallest pattern that addresses them.",
      "Implement roles through clear interfaces.",
      "Evaluate new complexity and alternatives.",
    ],
    "Observer can decouple event producers from subscribers; Strategy can swap pricing behavior; Adapter can normalize third-party APIs.",
    "Implement Strategy for delivery pricing, then show the simpler conditional it replaces and when the pattern is justified.",
    "const strategies = { standard: order => 50, express: order => 120 };\nconst shipping = strategies[type](order);",
  ),
  "javascript:Memory and performance": k(
    "JavaScript engines allocate objects, trace reachable values, reclaim unreachable memory, and optimize frequently executed code while the browser schedules rendering and other work.",
    "Leaks, excessive allocation, long tasks, layout thrashing, and premature optimization directly affect responsiveness and stability.",
    [
      "Measure a user-visible problem.",
      "Record CPU, allocation, network, and rendering evidence.",
      "Identify retained references or hot work.",
      "Change one bottleneck.",
      "Compare the same scenario.",
      "Protect the improvement with a budget or regression test.",
    ],
    "An event listener retaining a removed component can keep a large object graph alive until the listener is cleaned up.",
    "Profile a long list render, distinguish computation from paint cost, optimize one cause, and record before/after evidence.",
    "const handler = () => update(view);\nwindow.addEventListener('resize', handler);\n// cleanup: window.removeEventListener('resize', handler);",
  ),
  "javascript:Testing": k(
    "Testing executes software under controlled conditions and compares observable results with expectations at unit, integration, and end-to-end boundaries.",
    "Tests make refactoring safer, document contracts, catch regressions, and provide evidence—not proof—that important behavior works.",
    [
      "State the behavior and risk.",
      "Arrange minimal inputs and dependencies.",
      "Act through the public interface.",
      "Assert meaningful output or effect.",
      "Cover boundaries and failure cases.",
      "Keep tests deterministic and readable.",
    ],
    "A checkout unit test verifies total rules; an integration test verifies database transaction behavior; an end-to-end test verifies a user can place an order.",
    "Test a validation function with a table of valid, empty, malformed, boundary, and malicious-looking inputs.",
    "for (const [input, expected] of cases) {\n  test(`validates ${input}`, () => expect(validate(input)).toBe(expected));\n}",
  ),
  "javascript:Security basics": k(
    "Web security protects confidentiality, integrity, availability, and user control across untrusted input, code, identities, storage, and network boundaries.",
    "Client-side JavaScript processes attacker-controlled data and cannot enforce authorization; unsafe DOM or secret handling can compromise accounts.",
    [
      "Identify assets and trust boundaries.",
      "Validate and encode untrusted data for its output context.",
      "Enforce authentication and ownership on the server.",
      "Use HTTPS and secure cookie policies.",
      "Minimize dependencies and privileges.",
      "Log and respond without leaking sensitive details.",
    ],
    "Using textContent for a user label avoids interpreting it as HTML, while the server verifies that the current user owns any record they request.",
    "Threat-model a notes application for XSS, broken access control, CSRF, dependency risk, and sensitive local storage.",
    "output.textContent = untrustedText; // do not inject as HTML\n// authorization must still be enforced server-side",
  ),
};

export const getTopicKnowledge = (phaseId: string, topic: string) =>
  topics[`${phaseId}:${topic}`];
